mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib

presets:
  logsCollection:
    enabled: false
    includeCollectorLogs: false
    storeCheckpoints: false
    maxRecombineLogSize: 102400
  hostMetrics:
    enabled: false
  kubernetesAttributes:
    enabled: false
    extractAllPodLabels: false
    extractAllPodAnnotations: false
  kubeletMetrics:
    enabled: false
  kubernetesEvents:
    enabled: false
  clusterMetrics:
    enabled: false

configMap:
  create: true
  existingName: ""

command:
  name: "otelcol-contrib"

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc

  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"
        grpc:
          endpoint: "0.0.0.0:4317"
          
    hostmetrics:
      scrapers:
        cpu:
        disk:
        filesystem:
        load:
        memory:
        network:
        process:
        processes:
        paging:

  processors:
    batch:
      send_batch_max_size: 100000
      timeout: 5s

  exporters:
    kafka:
      brokers:
        - 'kafka:9092'

  extensions:
    health_check:
    pprof:
    zpages:

  service:
    telemetry:
      logs:
        level: info
    extensions: [health_check, pprof, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [kafka]
      metrics:
        receivers: [otlp, hostmetrics]
        processors: [batch]
        exporters: [kafka]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [kafka]
