---
# Source: opentelemetry-collector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-demo
  namespace: default
  labels:
    helm.sh/chart: opentelemetry-collector-0.93.1
    app.kubernetes.io/name: otelcol-demo
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "0.102.1"
    app.kubernetes.io/managed-by: Helm
    
data:
  relay: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"
          grpc:
            endpoint: "0.0.0.0:4317"
            
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
          process:
          processes:
          paging:

    processors:
      batch:
        send_batch_max_size: 100000
        timeout: 5s

    exporters:
      kafka:
        brokers:
          - 'kafka:9092'

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      telemetry:
        logs:
          level: info
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [kafka]
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [batch]
          exporters: [kafka]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [kafka]
