---
# Source: opentelemetry-collector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol-demo
  namespace: default
  labels:
    helm.sh/chart: opentelemetry-collector-0.93.1
    app.kubernetes.io/name: otelcol-demo
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "0.102.1"
    app.kubernetes.io/managed-by: Helm
    
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol-demo
      app.kubernetes.io/instance: example
      component: standalone-collector
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: d9e57f0179f085ef966263232b230fb81929f5792b3fb2cb85fbcf1c3e75b577
        
      labels:
        app.kubernetes.io/name: otelcol-demo
        app.kubernetes.io/instance: example
        component: standalone-collector
        
    spec:
      
      serviceAccountName: otelcol-demo
      securityContext:
        {}
      containers:
        - name: opentelemetry-collector
          args:
            - --config=/conf/relay.yaml
          securityContext:
            {}
          image: "otel/opentelemetry-collector-contrib"
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: otelcol-demo
            items:
              - key: relay
                path: relay.yaml
      hostNetwork: false
